spring.application.name=CulturalEvent
server.port=8085

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://ep-solitary-base-a5p5qt9h-pooler.us-east-2.aws.neon.tech/culturalevent?sslmode=require
spring.datasource.username=culturalevent_owner
spring.datasource.password=npg_9JZizNKf1sWw
spring.datasource.driver-class-name=org.postgresql.Driver