/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ucr.ac.cr.CulturalEvent.view;

import java.awt.event.ActionListener;
import ucr.ac.cr.CulturalEvent.model.User;

/**
 *
 * @author allis
 */
public class DialogUser extends javax.swing.JDialog {

    /**
     * Creates new form DialogUser
     */
    public DialogUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public User getUser() {
        User user = new User();
        if (this.txtId.getText().equals("")) {
            user.setId(0);
        } else {
            user.setId(Integer.parseInt(this.txtId.getText().toString()));
        }
        user.setId(Integer.parseInt(this.txtId.getText().toString()));
        user.setName(this.txtName.getText().toString());
        user.setEmail(this.txtEmail.getText().toString().trim());
        user.setTelephone(this.txtTelephone.getText());
        user.setUserType(this.cBoxUserType.getSelectedItem().toString());
        return user;
    }

    public void setUser(User user) {
        this.txtId.setText(String.valueOf(user.getId()));
        this.txtName.setText(user.getName());
        this.txtTelephone.setText(user.getTelephone());
        this.txtEmail.setText(user.getEmail());
        this.cBoxUserType.setSelectedItem(user.getUserType());
    }

    public void clean() {
        txtId.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtTelephone.setText("");
        cBoxUserType.setSelectedIndex(0);
    }

    public void setListen(ActionListener listener) {
        this.btnOk.addActionListener(listener);
        this.btnCancel.addActionListener(listener);
    }

    public String getId() {
        return this.txtId.getText();
    }

    public void setEnableID(boolean option) {
        this.txtId.setEnabled(option);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        cBoxUserType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setColumns(6);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        txtName.setColumns(10);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        txtEmail.setColumns(14);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        txtTelephone.setColumns(10);
        txtTelephone.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        getContentPane().add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        cBoxUserType.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        cBoxUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "User", "Organizer", " " }));
        getContentPane().add(cBoxUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telephone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("User type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        btnOk.setActionCommand("ok");
        btnOk.setContentAreaFilled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        btnCancel.setActionCommand("cancel");
        btnCancel.setContentAreaFilled(false);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UserRegisterFondo.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cBoxUserType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}//endClass
