/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ucr.ac.cr.CulturalEvent.view;

import java.awt.event.ActionListener;
import ucr.ac.cr.CulturalEvent.model.Event;

;

/**
 *
 * @author allis
 */
public class DialogEvent extends javax.swing.JDialog {

    /**
     * Creates new form DialogEvent
     */
    public DialogEvent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Event getEvent() {

        Event event = new Event();

        // Validar campo ID
        if (txtId.getText().trim().isEmpty()) {
            event.setId(0);
        } else {
            event.setId(Integer.parseInt(txtId.getText().trim()));
        }

        // Validar campo precio
        if (txtPrice.getText().trim().isEmpty()) {
            event.setPrice(0.0);
        } else {
            event.setPrice(Double.parseDouble(txtPrice.getText().trim()));
        }

        // Validar espacio disponible
        if (txtAvailableSpace.getText().trim().isEmpty()) {
            event.setAvailableSpace(0);
        } else {
            event.setAvailableSpace(Integer.parseInt(txtAvailableSpace.getText().trim()));
        }
        // Validar otros campos de texto
        event.setEventName(txtEventName.getText().trim());
        event.setDate(txtDate.getText().trim());
        event.setLocation(txtLocation.getText().trim());
        event.setTime(txtTime.getText().trim());
        event.setAddress(txtAddress.getText().trim());
        event.setDescription(txtDescription.getText().trim());
        event.setOrganizer(txtOrganizer.getText().trim());

        return event;
    }//endGetEvent

    public void setEvent(Event event) {
        this.txtId.setText(String.valueOf(event.getId()));
        this.txtEventName.setText(event.getEventName());
        this.txtDate.setText(event.getDate());
        this.txtLocation.setText(event.getLocation());
        this.txtTime.setText(event.getTime());
        this.txtAddress.setText(event.getAddress());
        this.txtPrice.setText(String.valueOf(event.getPrice()));
        this.txtDescription.setText(event.getDescription());
        this.txtOrganizer.setText(event.getOrganizer());
        this.txtAvailableSpace.setText(String.valueOf(event.getAvailableSpace()));
    }

    public void clean() {
        txtId.setText("");
        txtEventName.setText("");
        txtDate.setText("");
        txtLocation.setText("");
        txtTime.setText("");
        txtAddress.setText("");
        txtPrice.setText("");
        txtDescription.setText("");
        txtOrganizer.setText("");
        txtAvailableSpace.setText("");
    }

    public void setListen(ActionListener listener) {
        this.btnClose.addActionListener(listener);
        this.btnOk.addActionListener(listener);
    }

    public String getId() {
        return this.txtId.getText();
    }

    public void setEnableID(boolean option) {

        this.txtId.setEnabled(option);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtEventName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtOrganizer = new javax.swing.JTextField();
        txtAvailableSpace = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        txtDescription = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Location");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        btnOk.setActionCommand("ok");
        btnOk.setContentAreaFilled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        txtId.setColumns(6);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        txtEventName.setColumns(10);
        txtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        txtDate.setColumns(14);
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        txtLocation.setColumns(10);
        txtLocation.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        getContentPane().add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Event name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        txtTime.setColumns(10);
        txtTime.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Time");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        txtAddress.setColumns(10);
        txtAddress.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Organizer ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Available spaces");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtPrice.setColumns(10);
        txtPrice.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        txtOrganizer.setColumns(10);
        txtOrganizer.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txtOrganizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrganizerActionPerformed(evt);
            }
        });
        getContentPane().add(txtOrganizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        txtAvailableSpace.setColumns(10);
        txtAvailableSpace.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txtAvailableSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(txtAvailableSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        btnClose.setActionCommand("cancel");
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        txtDescription.setColumns(25);
        txtDescription.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Description");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EventRegisterFondo.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtOrganizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrganizerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrganizerActionPerformed

    private void txtAvailableSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailableSpaceActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAvailableSpace;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtOrganizer;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}//endClass
