/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.CulturalEvent.view;

import java.awt.event.ActionListener;

/**
 *
 * @author allis
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public FrmMenu() {
        initComponents();
    }
    
    public void listenMenu (ActionListener controller){
        this.mniEventRegister.addActionListener(controller);
        this.mniExit.addActionListener(controller);
        this.mniUserRegister.addActionListener(controller);
        this.mniEvents.addActionListener(controller);
        this.mniReserve.addActionListener(controller);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnExit = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        mnRegister = new javax.swing.JMenu();
        mniUserRegister = new javax.swing.JMenuItem();
        mniEventRegister = new javax.swing.JMenuItem();
        mnReservation = new javax.swing.JMenu();
        mniReserve = new javax.swing.JMenuItem();
        mnEvents = new javax.swing.JMenu();
        mniEvents = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuFondo.jpg"))); // NOI18N

        mnExit.setText("Exit");

        mniExit.setText("Exit");
        mnExit.add(mniExit);

        jMenuBar1.add(mnExit);

        mnRegister.setText("Register");

        mniUserRegister.setText("User Register");
        mniUserRegister.setActionCommand("UserRegister");
        mnRegister.add(mniUserRegister);

        mniEventRegister.setText("Event Register");
        mniEventRegister.setActionCommand("EventRegister");
        mnRegister.add(mniEventRegister);

        jMenuBar1.add(mnRegister);

        mnReservation.setText("Reservations");

        mniReserve.setText("Reservation");
        mnReservation.add(mniReserve);

        jMenuBar1.add(mnReservation);

        mnEvents.setText("Events");

        mniEvents.setText("view all available events");
        mniEvents.setActionCommand("ViewAvailableEvents");
        mnEvents.add(mniEvents);

        jMenuBar1.add(mnEvents);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnEvents;
    private javax.swing.JMenu mnExit;
    private javax.swing.JMenu mnRegister;
    private javax.swing.JMenu mnReservation;
    private javax.swing.JMenuItem mniEventRegister;
    private javax.swing.JMenuItem mniEvents;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniReserve;
    private javax.swing.JMenuItem mniUserRegister;
    // End of variables declaration//GEN-END:variables
}//endClass
