/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.CulturalEvent.view;

import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Johan Brenes
 */
public class FrmReport extends javax.swing.JFrame {

    /**
     * Creates new form FrmReport
     */
    public FrmReport() {
        initComponents();
    }

    public static void setMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public void setDataTable(String[][] data, String[] labels) {
        DefaultTableModel defaultTableModel = new DefaultTableModel(data, labels);
        tblReport.setModel(defaultTableModel);
        tblReport.setRowSorter(new TableRowSorter<>(defaultTableModel));
        jScrollPane1.setViewportView(tblReport);
    }

    public String[] getRowSelected() {
        int rowSelect = tblReport.getSelectedRow();
        String[] rowData = new String[tblReport.getColumnCount()];
        if (rowSelect != -1) {
            for (int i = 0; i < rowData.length; i++) {
                rowData[i] = tblReport.getValueAt(rowSelect, i).toString();
            }
            return rowData;
        } else {
            return new String[0];
        }
    }

    public void listenMouse(MouseListener controller) {
        tblReport.addMouseListener(controller);
    }

    public void filterByID() {
        DefaultTableModel modelTable = (DefaultTableModel) this.tblReport.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelTable);
        this.tblReport.setRowSorter(sorter);
        String textSearch = this.txtFilterID.getText();
        if (textSearch.length() == 0) {
            sorter.setRowFilter(null);
            this.tblReport.clearSelection();
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(textSearch, 0));
        }
    }

    public void listenKey(KeyListener controller) {
        txtFilterID.addKeyListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFilterID = new javax.swing.JTextField();
        panelButton1 = new ucr.ac.cr.CulturalEvent.view.PanelButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tblReport.setRowHeight(30);
        jScrollPane1.setViewportView(tblReport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 860, 310));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Filter By ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        txtFilterID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtFilterID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 94, -1));
        getContentPane().add(panelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, 89));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public PanelButton getPanelButton() {
        return this.panelButton1;
    }//endPanelButton 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private ucr.ac.cr.CulturalEvent.view.PanelButton panelButton1;
    private javax.swing.JTable tblReport;
    private javax.swing.JTextField txtFilterID;
    // End of variables declaration//GEN-END:variables
}//endClass
