/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.CulturalEvent.view;

import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Johan Brenes
 */
public class FrmReport extends javax.swing.JFrame {

    /**
     * Creates new form FrmReport
     */
    public FrmReport() {
        initComponents();
    }

    public static void setMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public void setDataTable(String[][] data, String[] labels) {
        DefaultTableModel defaultTableModel = new DefaultTableModel(data, labels);
        tblReport.setModel(defaultTableModel);
        tblReport.setRowSorter(new TableRowSorter<>(defaultTableModel));
        jScrollPane1.setViewportView(tblReport);
    }

    public String[] getRowSelected() {
        int rowSelect = tblReport.getSelectedRow();
        String[] rowData = new String[tblReport.getColumnCount()];
        if (rowSelect != -1) {
            for (int i = 0; i < rowData.length; i++) {
                rowData[i] = tblReport.getValueAt(rowSelect, i).toString();
            }
            return rowData;
        } else {
            return new String[0];
        }
    }

    public void listenMouse(MouseListener controller) {
        tblReport.addMouseListener(controller);
    }

    public void filterByID() {
        DefaultTableModel modelTable = (DefaultTableModel)tblReport.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelTable);
        tblReport.setRowSorter(sorter);
        String textSearch = txtFilterID.getText();
        if (textSearch.length() == 0) {
            sorter.setRowFilter(null);
            tblReport.clearSelection();
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(textSearch, 0));
        }
    }

    public void listenKey(KeyListener controller) {
        txtFilterID.addKeyListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFilterID = new javax.swing.JTextField();
        panelButton1 = new ucr.ac.cr.CulturalEvent.view.PanelButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        jLabel1.setText("Filter By ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFilterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public PanelButton getPanelButton() {
        return this.panelButton1;
    }//endPanelButton 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private ucr.ac.cr.CulturalEvent.view.PanelButton panelButton1;
    private javax.swing.JTable tblReport;
    private javax.swing.JTextField txtFilterID;
    // End of variables declaration//GEN-END:variables
}
