/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.CulturalEvent.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import ucr.ac.cr.CulturalEvent.model.Event;
import ucr.ac.cr.CulturalEvent.model.User;

/**
 *
 * @author allis
 */
public class FrmReservation extends javax.swing.JFrame {

    /**
     * Creates new form frmReservation
     */
    public FrmReservation() {
        initComponents();
    }

    //Este metodo recibe el arreglo y rellena el comboBox
    public void setCBoxUsers(String[] listUsers) {
        this.cboxUsers.setModel(new DefaultComboBoxModel<>(listUsers));
    }

    public void listenCBoxUsers(ActionListener controller) {
        this.cboxUsers.addActionListener(controller);
    }

    //devuelve el index
    public int getCBoxUserIndex() {
        return this.cboxUsers.getSelectedIndex();
    }

    //llena los labels
    public void setUserLabels(User user) {
        this.lblID.setText("ID: " + user.getId());
        this.lblName.setText("Name: " + user.getName());
        this.lblTelefono.setText("Telephone: " + user.getTelephone());
        this.lblUserType.setText("User type: " + user.getUserType());
    }

    public void setTblEvent(String[][] data, String[] labels) {
        this.tblEvent.setModel(new DefaultTableModel(data, labels));
        this.jScrollPane3.setViewportView(this.tblEvent);
    }

    public int getRowIDSpace() {
        int rowSelected = this.tblEvent.getSelectedRow();
        return Integer.parseInt(this.tblEvent.getValueAt(rowSelected, 0).toString());
    }

    public void listenMouseTbl(MouseListener controller) {
        this.tblEvent.addMouseListener(controller);
    }

    public void addReserveTable(Event event, int availableSpaces, double total) {
        DefaultTableModel model = (DefaultTableModel) this.tblReservation.getModel();
        model.addRow(new String[]{String.valueOf(event.getId()),
            event.getEventName(),
            event.getDate(),
            event.getLocation(),
            event.getTime(),
            String.valueOf(event.getPrice()),
            String.valueOf(availableSpaces),
            String.valueOf(total)});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tblReservation = new javax.swing.JTable();
        cboxUsers = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        lblTelefono = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Event", "Date", "Location", "Time", "Price", "Spaces", "Total"
            }
        ));
        jScrollPane4.setViewportView(tblReservation);

        cboxUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxUsers.setActionCommand("cBoxUsers");
        cboxUsers.setPreferredSize(new java.awt.Dimension(130, 26));
        cboxUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxUsersActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("User:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jButton1.setActionCommand("close");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEvent.setIntercellSpacing(new java.awt.Dimension(1, 1));
        tblEvent.setRowHeight(30);
        tblEvent.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tblEvent);

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTelefono.setText("jLabel4");

        lblID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblID.setText("jLabel2");

        lblName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblName.setText("jLabel3");

        lblUserType.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblUserType.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Reservations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUserType)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(cboxUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblName)
                            .addComponent(lblID)
                            .addComponent(lblTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(415, 415, 415)
                        .addComponent(jButton1)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(20, 20, 20)
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(lblTelefono)
                                .addGap(26, 26, 26)
                                .addComponent(lblUserType))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cboxUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(197, 197, 197))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxUsersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxUsers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JTable tblEvent;
    private javax.swing.JTable tblReservation;
    // End of variables declaration//GEN-END:variables
}//endClass
