/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.CulturalEvent.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import ucr.ac.cr.CulturalEvent.model.Event;
import ucr.ac.cr.CulturalEvent.model.User;

/**
 *
 * @author allis
 */
public class FrmReservation extends javax.swing.JFrame {

    /**
     * Creates new form frmReservation
     */
    public FrmReservation() {
        initComponents();
    }

    //Este metodo recibe el arreglo y rellena el comboBox
    public void setCBoxUsers(String[] listUsers) {
        this.cboxUsers.setModel(new DefaultComboBoxModel<>(listUsers));
    }

    public void listenCBoxUsers(ActionListener controller) {
        this.cboxUsers.addActionListener(controller);
    }

    //devuelve el index
    public int getCBoxUserIndex() {
        return this.cboxUsers.getSelectedIndex();
    }

    //llena los labels
    public void setUserLabels(User user) {
        this.lblID.setText("ID: " + user.getId());
        this.lblName.setText("Name: " + user.getName());
        this.lblTelefono.setText("Telephone: " + user.getTelephone());
        this.lblUserType.setText("User type: " + user.getUserType());
    }

    public void setTblEvent(String[][] data, String[] labels) {
        this.tblEvent.setModel(new DefaultTableModel(data, labels));
        this.jScrollPane3.setViewportView(this.tblEvent);
    }

    public int getRowIDSpace() {
        int rowSelected = this.tblEvent.getSelectedRow();
        return Integer.parseInt(this.tblEvent.getValueAt(rowSelected, 0).toString());
    }

    public void listenMouseTbl(MouseListener controller) {
        this.tblEvent.addMouseListener(controller);
    }

    public void addReserveTable(Event event, int availableSpaces, double total) {
        DefaultTableModel model = (DefaultTableModel) this.tblReservation.getModel();
        model.addRow(new String[]{String.valueOf(event.getId()),
            event.getEventName(),
            event.getDate(),
            event.getLocation(),
            event.getTime(),
            String.valueOf(event.getPrice()),
            String.valueOf(availableSpaces),
            String.valueOf(total)});
    }

    public void waitingUsers(int users){
        lblWaiting.setText("Waiting Users: " +users);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWaiting = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReservation = new javax.swing.JTable();
        cboxUsers = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        lblTelefono = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWaiting.setForeground(new java.awt.Color(0, 0, 0));
        lblWaiting.setText("jLabel5");
        getContentPane().add(lblWaiting, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Waiting Users");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        tblReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Event", "Date", "Location", "Time", "Price", "Spaces", "Total"
            }
        ));
        jScrollPane4.setViewportView(tblReservation);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 780, 167));

        cboxUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxUsers.setActionCommand("cBoxUsers");
        cboxUsers.setPreferredSize(new java.awt.Dimension(130, 26));
        cboxUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxUsersActionPerformed(evt);
            }
        });
        getContentPane().add(cboxUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("User:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jButton1.setActionCommand("close");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 510, -1, -1));

        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEvent.setIntercellSpacing(new java.awt.Dimension(1, 1));
        tblEvent.setRowHeight(30);
        tblEvent.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tblEvent);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 780, 170));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono.setText("jLabel4");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lblID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("jLabel2");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("jLabel3");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        lblUserType.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(0, 0, 0));
        lblUserType.setText("jLabel2");
        getContentPane().add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxUsersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxUsers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblWaiting;
    private javax.swing.JTable tblEvent;
    private javax.swing.JTable tblReservation;
    // End of variables declaration//GEN-END:variables
}//endClass
